export const SECURITY_VALIDATOR_CONFIG = {
  TOKEN_VALIDATION_BATCH_SIZE: 5,
  MIN_ETH_LIQUIDITY: "2",
  TOKEN_ACTIVE_DURATION_MS: 10 * 60 * 1000,
  TOKEN_VALIDATION_INTERVAL_MS: 60 * 1000,
  USD_TEST_AMOUNT: 0.01,
};
