openapi: 3.0.0
info:
  title: Market Sage API
  version: 1.0.0
  description: MarketSage API for discovery, secrity validation, and monitoring

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Token Discovery
    description: Token discovery operations
  - name: Token Security Validation
    description: Token security validation operations
  - name: Token Monitoring
    description: Token monitoring operations
  - name: System
    description: System operations and health checks

paths:
  /token-discovery/status:
    get:
      summary: Token discovery service status
      description: Returns the current status of the token discovery service
      tags:
        - Token Discovery
      responses:
        "200":
          description: Token discovery service status
          content:
            application/json:
              schema:
  /token-discovery/start:
    post:
      summary: Start token discovery service
      description: Starts the token discovery service
      tags:
        - Token Discovery
      responses:
        "200":
          description: Token discovery service started
          content:
            application/json:
              schema:
  /token-discovery/stop:
    post:
      summary: Stop token discovery service
      description: Stops the token discovery service
      tags:
        - Token Discovery
      responses:
        "200":
          description: Token discovery service stopped
          content:
            application/json:
              schema:

  /token-security-validator/status:
    get:
      summary: Token security validator status
      description: Returns the current status of the token security validator
      tags:
        - Token Security Validation
      responses:
        "200":
          description: Token security validator status
          content:
            application/json:
              schema:
  /token-security-validator/validate:
    post:
      summary: Validate token security
      description: Validates the security of a token
      tags:
        - Token Security Validation
      responses:
        "200":
          description: Token security validated
          content:
            application/json:
              schema:

  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      tags:
        - System
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  version:
                    type: string
                    example: "1.0.0"

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
