openapi: 3.0.0
info:
  title: Market Sage API
  version: 1.0.0
  description: API for token discovery, validation, and monitoring

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Discovery
    description: Token discovery operations
  - name: Security
    description: Token security validation operations
  - name: Monitor
    description: Token monitoring operations
  - name: System
    description: System operations and health checks

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      tags:
        - System
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  version:
                    type: string
                    example: "1.0.0"

  /services/status:
    get:
      summary: Services status check
      description: Returns the status of all background services including the token security validator and monitor
      tags:
        - System
      responses:
        "200":
          description: Services status information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      isInitialized:
                        type: boolean
                        example: true
                      tokenSecurityValidator:
                        type: object
                        properties:
                          isRunning:
                            type: boolean
                            example: true
                          queueSize:
                            type: integer
                            example: 0
                          isProcessingToken:
                            type: boolean
                            example: false
                          health:
                            type: string
                            enum: [healthy, degraded, stopped]
                            example: "healthy"
                          consecutiveErrors:
                            type: integer
                            example: 0
                      tokenMonitorManager:
                        type: object
                        properties:
                          isRunning:
                            type: boolean
                            example: true
                          queueSize:
                            type: integer
                            example: 0
        "500":
          description: Error retrieving services status
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Failed to get services status"

  # Example Discovery endpoint
  /discovery/status:
    get:
      summary: Get discovery service status
      description: Returns the current status of the token discovery service
      tags:
        - Discovery
      responses:
        "200":
          description: Discovery service status
          content:
            application/json:
              schema:
                type: object
                properties:
                  running:
                    type: boolean
                    example: true
                  startBlock:
                    type: integer
                    example: 1234567
                  currentBlock:
                    type: integer
                    example: 1234600

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
