export const TRADING_CONFIG = {
  USD_BUY_SIZE: 20,
  PROFIT_MARGIN: 1.21,
  STOP_LOSS_MARGIN: 0.9,
  SLIPPAGE_TOLERANCE: 0.02,
  MAX_PRICE_IMPACT_PERCENTAGE: 5,
  TP1_POSITION_PERCENTAGE: 1,
  MAX_RETRIES: 3,
};
